def handle_err(err):
    print(str(err))
    raise Exception(err)
